### ISSUE TITLE
What is the Z-score of a point with invalid left and right Z-scores? 

### ISSUE THREAD

**Issue by julianstanley** [miraep8/rendseq#10]
https://github.com/miraep8/rendseq/blob/b0ee9ff0caad65864b8d374341a38c0f8a3ad6ca/rendseq/zscores.py#L125-L127

If z-score is not valid on either the left or the right side of a point, e.g. a long span of the same values, what should the z-score of that point be?

Here, it seems like it says that if the value of that point is 3, then the z-score of that point should be 2? Is that correct?

I think a decent Z-score in this edge case would be 0.

**Comment by miraep8** [comment]
Yea!  That was the intention.  :)  The reasoning behind this is - dividing by 1.5 puts a small damper on potential just background noise.  Ie - a position with <10 reads likely won't be about our threshold if we are using a thresholding approach, and will likely still not be counted as a peak in the HMM either.  However, as we start to get beyond 10, this position looks more and more like a potentially interesting peak candidate, though perhaps for a very lowly expressed transcription isoform. 

In truth - it really begs the question - do we care about being able to characterize lowly expressed transcription isoforms.  The answer to that question may in fact be no - especially given that many of the downstream analyses one might want to do may ultimately filter based on read density.  In which case, your suggestion of setting the z score to 0 makes sense!  However I imagine there also would be cases where one wants to be able to use those lowly expressed regions - for example you might still be able to use them in a transcription isoform calling approach or similar! 

Either way - I think it would be useful to make it clearer to the user which assumption we are baking into this case.  Perhaps defaulting to 0 is not such a bad idea, and then we could provide guidance on how to change some of the z score parameters (eg increasing window size/decreasing the minimum reads threshold) if they want to catch more lowly expressed transcripts?

Thanks for bringing this up!

**Comment by julianstanley** [comment]
Ahh, that's really interesting. So you can imagine, with window size of 10, gap size of 1, and a minimum bg read cutoff of 5 on either side, a read like this:

1 0 3 1 0 1 **120** 3 1 1 0 2 0

And that wouldn't make our cutoff, but could well be a real peak. That's what your referring to, right?

This seems like a challenging peak to call. My first thought was to maybe include the peak in background read cutoff minimum. But then a peak like this:

0 0 1 0 0 **1900** 0 0 1 0 0

Would get a tremendously high Z-score.

(Note that the peak above also gets a very high Z-score in the current method, which is part of why I think defaulting to 0 is more appropriate).

I think maybe we could consider both a peak-included background cutoff and a peak-excluded background cutoff? But probably good to leave this issue open and think on it more.

**Comment by miraep8** [comment]
I really like your suggestion of including the position value itself in the minimum reads calculation.  This seams like a good balance to me of leaving ourselves open to catching peaks surrounded by low read density, but which are themselves quite high.   I also think this solution is easy to understand and communicate and doesn't add the complication of 2 different cutoffs. 

Shall we make a PR to incorporate this change?

> But then a peak like this:
> 
> 0 0 1 0 0 **1900** 0 0 1 0 0
> 
> Would get a tremendously high Z-score.
> 
> (Note that the peak above also gets a very high Z-score in the current method, which is part of why I think defaulting to 0 is more appropriate).
> 
> I think maybe we could consider both a peak-included background cutoff and a peak-excluded background cutoff? But probably good to leave this issue open and think on it more.

Personally I am ok with this getting a really high z score. I think this would be an interesting feature in the data and worth flagging.  At the same time it doesn't necessarily seem like a super biologically relevant example?  I was more thinking about something like this:

0 0 1 0 0 **15** 0 0 1 0 0

**Comment by julianstanley** [comment]
Perfect, that sounds good! I'll incorporate that in the PR that includes the tests (and some other small tweaks).

**Comment by miraep8** [comment]
Sounds good! Thanks!
