### ISSUE TITLE
Add some basic test cases

### ISSUE THREAD

**Issue by miraep8** [miraep8/rendseq#2]
Currently we don't have any fleshed out test cases!  This is not good because it makes it hard to improve the code without breaking it!  May I suggest that we make use of the library pytest?  Then the work flow can include a run of the test suite before initiating a pull request. 

As a first pass we can just test that each of the functions doesn't error out and only accepts/returns the expected types. 

Later we can add more tests that check that check the accuracy of certain method's abilities to call peaks or calculate zscores etc.

**Comment by julianstanley** [comment]
I'll work on this!

Need tests for:

file_funcs.py
- [ ] write_wig
- [ ] open_wig
- [ ] make_new_dir

make_peaks.py
- [ ] populate_trans_mat
- [ ] hmm_peaks
- [ ] make_kink_fig
- [ ] calc_thresh
- [ ] thresh_peaks

zscores.py
- [ ] adjust_down
- [ ] adjust_up
- [ ] remove_outliers
- [ ] calc_score
- [ ] l_score_helper
- [ ] r_score_helper
- [ ] z_scores

**Comment by miraep8** [comment]
Sounds great!  Thanks for taking a look at this!

**Comment by miraep8** [comment]
Also - just to check - I would really like to run all tests using the pytest library!  If you could make sure that any tests you write are compatible with that would be nice. If you would like I could add a few tests first to demo what that would look like
