### ISSUE TITLE
Vectorize functions

### ISSUE THREAD

**Issue by conniesaur** [miraep8/rendseq#7]
Some of the slower running functions (zscore calculation, HMM peak calling) could be sped up by vectorizing the operations currently happening within for loops. This would also speed up parameter searches/testing where these functions would be run repeatedly!

**Comment by miraep8** [comment]
Great suggestion! :)  Lets do it! :) Oh man, multiple parameter searches happening repeatedly! So bad haha.  I went ahead and assigned you but happy to jump in as well.
