### ISSUE TITLE
Should file_funcs take a file handle instead?

### ISSUE THREAD

**Issue by julianstanley** [miraep8/rendseq#8]
While going to test file_funcs (#2), I remembered that writing files for testing isn't always the best option. 

See this [SO post on the topic](https://stackoverflow.com/questions/3942820/how-to-do-unit-testing-of-functions-writing-files-using-pythons-unittest).

I think I'm going to use `unittest.mock` to fix that problem, but wanted to post here in case that's not ideal.

----------

**More detail**

Our options are:

1. Rewrite [write_wig](https://github.com/julianstanley/rendseq/blob/b0ee9ff0caad65864b8d374341a38c0f8a3ad6ca/rendseq/file_funcs.py#L10) and [open_wig](https://github.com/julianstanley/rendseq/blob/b0ee9ff0caad65864b8d374341a38c0f8a3ad6ca/rendseq/file_funcs.py#L26) to accept file handles instead of file names.

Advantage: Scales more easily, plus is the top response on the SO post.
Disadvantage: Reading/writing from filehandles is a little less intuitive. (Will users interact with write_wig and open_wig directly?)

2. read/write files in tests, deleting files that match the tests and keeping the ones that don't. 

Advantage: More intuitive, plus you have a nice output file for things that don't match.
Disadvantage: IO gets confused when lots are tests are being run, especially in parallel (a la pytest).

3. Use `mock_open` to not write actual files, but a place in memory that pretends to be a file.

This is an intermediate between the two other options--doesn't bug up IO. I think this might be the way to go--it's lower-down on the answers in SO, but mock_open wasn't available until recently. 

Let me know if you have a preference for any of these options!

**Comment by miraep8** [comment]
Hey! 

As mentioned briefly in #2 I think it would be best if we made use of a unified testing library for writing our tests.  I would really recommend we stick with pytest! :)  I think there is a way to check writing of files using pytest as well.  See [this SO post](https://stackoverflow.com/questions/20531072/writing-a-pytest-function-to-check-outputting-to-a-file-in-python)! Let me know if you don't think this solution will work for us.

**Comment by julianstanley** [comment]
Thanks for the comment--absolutely using pytest! 

Mocks and using IO handles also works just fine with pytest. e.g. [this example](https://github.com/idjaw/testing_example/blob/master/tests/test_my_code.py), even though pytest can run unittest-style tests just fine--[as mentioned here](https://blog.j-labs.pl/2019/02/Pytest-why-its-more-popular-than-unittest).

The problem is more general: even with temporary directories (as in your example), writing to files in tests can create problems when you scale up. That's why alternatives like monkeypatch and mock are so popular. 

Anyways, I'm sure our tests won't get so big for that to matter, so I'll just go with the tmpdir route you recommended.
